# Generated by Django 4.2.5 on 2023-09-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_address1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address1',
        ),
    ]
