# Generated by Django 4.2.5 on 2023-09-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_flash_sales_product_image_product_top_deal_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
