# Generated by Django 4.2.5 on 2023-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank='', default='', null=True, upload_to='product_img/'),
        ),
    ]
