# Generated by Django 4.2.5 on 2023-09-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
