# Generated by Django 4.2.6 on 2023-10-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
