# Generated by Django 4.2.6 on 2023-10-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soled_item',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
