# Generated by Django 4.2.6 on 2023-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, choices=[('N', 'Newest'), ('B', 'Best Seller'), ('MV', 'Most Visited'), ('HQ', 'Highest Quality')], default='', max_length=2, null=True),
        ),
    ]
