# Generated by Django 4.2.6 on 2023-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
