# Generated by Django 4.2.6 on 2023-10-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
    ]
