# Generated by Django 4.2.6 on 2023-11-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='product_img/no-image-placeholder.png', null=True, upload_to='product_img/'),
        ),
    ]
