# Generated by Django 4.2.6 on 2023-11-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='product_img/no-image-placeholder.png', upload_to='product_img/'),
        ),
    ]
