# Generated by Django 4.2.5 on 2023-09-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractivation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivation',
        ),
    ]
