# Generated by Django 4.2.5 on 2023-09-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
