# Generated by Django 4.2.6 on 2023-10-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
