# Generated by Django 4.2.6 on 2023-10-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
